# Generated by Django 4.1.5 on 2023-01-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Movie',
        ),
    ]
