# Generated by Django 4.1.5 on 2023-01-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_director_alter_movie_director_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='images/titles/'),
        ),
    ]
