# Generated by Django 4.1.5 on 2023-01-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(upload_to='images/'),
            preserve_default=False,
        ),
    ]
