# Generated by Django 4.1.5 on 2023-01-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_director_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
