# Generated by Django 4.1.5 on 2023-01-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_director_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
