# Generated by Django 4.1.5 on 2023-01-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_rename_image_movie_movieimage_movie_directorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='directorimage',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieimage',
            field=models.ImageField(default='', upload_to='images/titles/'),
        ),
    ]
