# Generated by Django 4.1.5 on 2023-01-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_movie_directorimage_alter_movie_movieimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genreimage',
            field=models.ImageField(default='', upload_to='images/genres/'),
        ),
    ]
