# Generated by Django 4.1.5 on 2023-02-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_director_avg_rating_alter_director_num_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
