# Generated by Django 4.1.5 on 2023-02-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genreimage',
        ),
    ]
