# Generated by Django 4.1.5 on 2023-02-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_remove_movie_genreimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genreimage',
            field=models.ImageField(default='', upload_to='images/genres/'),
        ),
    ]
