# Generated by Django 4.1.5 on 2023-02-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_movie_genreimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genreimage',
        ),
    ]
