# Generated by Django 4.1.5 on 2023-02-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_remove_movie_genreimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directorimage',
            field=models.ImageField(default='', upload_to='images/directors'),
        ),
    ]
