# Generated by Django 4.1.5 on 2023-02-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_movie_director_alter_movie_directorimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='no director', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directorimage',
            field=models.ImageField(blank=True, default='images/default/default_director.jpg', upload_to='images/directors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, default='no genre', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieimage',
            field=models.ImageField(blank=True, default='images/default/default_movie.jpg', upload_to='images/titles/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='star1',
            field=models.CharField(blank=True, default='no star', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='star2',
            field=models.CharField(blank=True, default='no star', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='timeswatched',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, default='no title', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
